version: '2'

networks:
  hlf11:

services:
  # define orderer container
  orderer.hlf11.com.au:
    image: hyperledger/fabric-orderer:x86_64-1.1.0  
    container_name: orderer.hlf11.com.au
    environment: 
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    volumes:
      - ./orderer/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/hlf11.com.au/orderers/orderer.hlf11.com.au/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/hlf11.com.au/users/Admin@hlf11.com.au/msp:/var/hyperledger/orderer/users/msp
      - ./orderer.hlf11.com.au:/var/hyperledger/production/orderer 

    command: orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 7050:7050
    networks:
      - hlf11

  # define all the peer containers
  peer0.org1.com.au:
    container_name: peer0.org1.com.au
    extends: 
      file: ./peer.yaml
      service: peer
    environment: 
      - CORE_PEER_ID=peer0.org1.com.au
      - CORE_PEER_ADDRESS=peer0.org1.com.au:7051
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/  
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.com.au:7051
    volumes: 
      - ./crypto-config/peerOrganizations/org1.com.au/peers/peer0.org1.com.au/msp:/etc/hyperledger/msp/peer  
      - ./crypto-config/peerOrganizations/org1.com.au/users/Admin@org1.com.au/msp:/etc/hyperledger/msp/users
      - ./peer0.org1.com.au:/var/hyperledger/production
      
    ports:
      - 8051:7051
      - 8053:7053
    depends_on: 
      - orderer.hlf11.com.au
    networks: 
      - hlf11  

  peer0.org2.com.au:
    container_name: peer0.org2.com.au
    extends: 
      file: ./peer.yaml
      service: peer
    environment: 
      - CORE_PEER_ID=peer0.org2.com.au
      - CORE_PEER_ADDRESS=peer0.org2.com.au:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/  
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.com.au:7051
    volumes: 
      - ./crypto-config/peerOrganizations/org2.com.au/peers/peer0.org2.com.au/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/org2.com.au/users/Admin@org2.com.au/msp:/etc/hyperledger/msp/users   
      - ./peer0.org2.com.au:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
    depends_on: 
      - orderer.hlf11.com.au
    networks: 
      - hlf11 

  # define cli container for each peer 
  cli.org1:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.org1
    environment: 
     - CORE_PEER_ID=cli.org1.com.au
     - CORE_PEER_ADDRESS=peer0.org1.com.au:7051
     - CORE_PEER_LOCALMSPID=org1MSP
     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.com.au/msp
    volumes:
     - ./crypto-config/peerOrganizations/org1.com.au:/etc/hyperledger/msp
     - ./crypto-config/peerOrganizations/org2.com.au:/etc/hyperledger/org2/msp
     - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    depends_on:
     - orderer.hlf11.com.au
     - peer0.org1.com.au
   
    networks: 
    - hlf11

  cli.org2:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.org2
    environment: 
      - CORE_PEER_ID=cli.org2.com.au
      - CORE_PEER_ADDRESS=peer0.org2.com.au:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org2.com.au/msp
    volumes:
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./crypto-config/peerOrganizations/org2.com.au:/etc/hyperledger/msp
    depends_on:
      - orderer.hlf11.com.au
      - peer0.org2.com.au
    networks: 
     - hlf11

  cli:
    container_name: cli
    extends: 
      file: base/cli-base.yaml 
      service: cli-base 
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.com.au:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_LOCALMSPTYPE=bccsp
      #- CORE_PEER_TLS_ENABLED=true
      #- CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.com.au/peers/peer0.org1.com.au/tls/server.crt
      #- CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.com.au/peers/peer0.org1.com.au/tls/server.key
      #- CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.com.au/peers/peer0.org1.com.au/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.com.au/users/Admin@org1.com.au/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./orderer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
        - ./chaincode:/opt/gopath/src/
        - ./channels/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channels
        
    depends_on:
      - orderer.hlf11.com.au
      - peer0.org1.com.au
      #- peer1.org1.com.au
      - peer0.org2.com.au
      #- peer1.org2.com.au
    networks: 
     - hlf11