version: '2'

services:
  cli-base:
    tty: true
    image: hyperledger/fabric-tools:x86_64-1.1.0
 
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - /var/run/:/host/var/run/
      - ../orderer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
      - ../chaincode:/opt/gopath/src/
      - ../channels/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channels
      - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      
      
     
    
     