# Admin and Peer certificate will be created automatically by cryptogen.exec
#Imp 
  #spacing after : is important
  # Tab spacing is maintained   


# "PeerOrgs" - Definition of organizations managing peer nodes
PeerOrgs:
  - Name: org3 # Third organisation 
    Domain: org3.com.au
    EnableNodeOUs: true # ability to classify identities as either a “client” or a “peer”. 
    Template:
      Count: 2 #define no. of peers in this organisation
    Users:
      Count: 1 #Number of users Identity for an organization.
  


