NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org3.com.au-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org3.com.au-cert.pem
    OrganizationalUnitIdentifier: peer
